Repository CycloneDX/cyclonedx-core-java, pull requests merged in 2024-09, with the labels that each got.

#493 Fix Issue 462
  src/main/java/org/cyclonedx/model/Service.java
  src/test/java/org/cyclonedx/parsers/AbstractParserTest.java
  src/test/java/org/cyclonedx/parsers/JsonParserTest.java
  src/test/java/org/cyclonedx/parsers/XmlParserTest.java
  src/test/resources/bom-1.5.json
  src/test/resources/bom-1.5.xml
Labels: bug, enhancement

#502 Fix Issue 385
  src/main/java/org/cyclonedx/util/LicenseResolver.java
  src/test/java/org/cyclonedx/util/LicenseResolverTest.java
Labels: bug

#504 Code Improvements
  src/main/java/org/cyclonedx/generators/json/BomJsonGenerator.java
  src/main/java/org/cyclonedx/generators/xml/BomXmlGenerator.java
  src/main/java/org/cyclonedx/model/Annotation.java
  src/main/java/org/cyclonedx/model/Evidence.java
  src/main/java/org/cyclonedx/model/attestation/Attestation.java
  src/main/java/org/cyclonedx/model/attestation/Claim.java
  src/main/java/org/cyclonedx/model/attestation/Declarations.java
  src/main/java/org/cyclonedx/model/attestation/affirmation/Affirmation.java
  src/main/java/org/cyclonedx/model/attestation/affirmation/Signatory.java
  src/main/java/org/cyclonedx/model/attestation/evidence/Evidence.java
  src/main/java/org/cyclonedx/model/component/crypto/AlgorithmProperties.java
  src/main/java/org/cyclonedx/model/definition/Standard.java
  src/main/java/org/cyclonedx/model/vulnerability/ProofOfConcept.java
  src/main/java/org/cyclonedx/model/vulnerability/Vulnerability.java
  src/main/java/org/cyclonedx/util/deserializer/AttachmentTextDeserializer.java
  src/main/java/org/cyclonedx/util/serializer/SignatorySerializer.java
  src/test/java/org/cyclonedx/BomJsonGeneratorTest.java
  src/test/java/org/cyclonedx/BomXmlGeneratorTest.java
Labels: enhancement

#499 Polish Code
  src/main/java/org/cyclonedx/CycloneDxMediaType.java
  src/main/java/org/cyclonedx/Format.java
  src/main/java/org/cyclonedx/generators/AbstractBomGenerator.java
  src/main/java/org/cyclonedx/model/ComponentWrapper.java
  src/main/java/org/cyclonedx/parsers/JsonParser.java
  src/main/java/org/cyclonedx/util/BomLink.java
  src/main/java/org/cyclonedx/util/deserializer/MetadataDeserializer.java
  src/main/java/org/cyclonedx/util/deserializer/SignatoryDeserializer.java
  src/main/java/org/cyclonedx/util/serializer/EvidenceSerializer.java
  src/main/java/org/cyclonedx/util/serializer/ExternalReferenceSerializer.java
  src/main/java/org/cyclonedx/util/serializer/HashSerializer.java
  src/main/java/org/cyclonedx/util/serializer/PropertiesSerializer.java
  src/main/java/org/cyclonedx/util/serializer/SerializerUtils.java
Labels: enhancement

#506 Enhancements and polish code
  src/main/java/org/cyclonedx/model/attestation/Attestation.java
  src/main/java/org/cyclonedx/model/attestation/Claim.java
  src/main/java/org/cyclonedx/model/attestation/affirmation/Signatory.java
  src/main/java/org/cyclonedx/model/definition/Standard.java
  src/main/java/org/cyclonedx/model/vulnerability/ProofOfConcept.java
  src/main/java/org/cyclonedx/util/deserializer/ExpressionDeserializer.java
  src/main/java/org/cyclonedx/util/deserializer/SignatoryDeserializer.java
  src/main/java/org/cyclonedx/util/serializer/SignatorySerializer.java
Labels: enhancement

#508 Fix NPE when deserializing `OrganizationalEntity` without name
  src/main/java/org/cyclonedx/util/deserializer/OrganizationalChoiceDeserializer.java
  src/test/java/org/cyclonedx/parsers/JsonParserTest.java
  src/test/resources/regression/issue507.json
Labels: bug
